### PR TITLE
bugfix: fix color collection schema

### PR DESCRIPTION
**Pull request by daniel-lopes-optimizely**
Follow up fix to #54 

Fixes the previous schema change from Set to List colour collection types.

Current error:
```
Stack trace from the terraform-provider-looker_v0.2.14 plugin:

panic: interface conversion: interface *** is []interface ***, not *schema.Set

goroutine 66 [running]:
github.com/devoteamgcloud/terraform-provider-looker/internal/provider.cocoSchemaToStruct(***0xc000662f00?, 0xd8c884?***, 0xec7d58?, 0xc00032ac00)
	github.com/devoteamgcloud/terraform-provider-looker/internal/provider/resource_color_collection.go:183 +0xff5
github.com/devoteamgcloud/terraform-provider-looker/internal/provider.resourceColorCollectionUpdate(***0xec7d58, 0xc000662f00***, 0xc00011fd00, ***0xc18be0?, 0xc00052fd70?***)
	github.com/devoteamgcloud/terraform-provider-looker/internal/provider/resource_color_collection.go:330 +0x265
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0000ff880, ***0xec7d90, 0xc00052cae0***, 0xd?, ***0xc18be0, 0xc00052fd70***)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000ff880, ***0xec7d90, 0xc00052cae0***, 0xc0001911e0, 0xc00011fb80, ***0xc18be0, 0xc00052fd70***)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x82c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d1d0, ***0xec7ce8?, 0xc000550580?***, 0xc00051a2d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000ce5a0, ***0xec7d90?, 0xc00052c180?***, 0xc0000e4000)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(***0xd4b320?, 0xc0000ce5a0***, ***0xec7d90, 0xc00052c180***, 0xc000662060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000b2700, ***0xecb5a8, 0xc000460ea0***, 0xc0001d2120, 0xc000445170, 0x14a6ae0, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:[128](https://github.com/ZaiusInc/reporting-app/actions/runs/5279015277/jobs/9549137870#step:4:134)3 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0000b2700, ***0xecb5a8, 0xc000460ea0***, 0xc0001d2120, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-looker_v0.2.14 plugin crashed!
```

### CODE REVIEW

**Comment by daniel-lopes-optimizely** [comment]
@Nabil-Lahssini can you take a look?

**Review by Nabil-Lahssini — CHANGES_REQUESTED** [review]
Still errors after fix, I will momentarily revert all changes and approve when PR fixes the bug
image

**Comment by daniel-lopes-optimizely** [comment]
@Nabil-Lahssini how are you testing this? Maybe I can do the same.

**Comment by daniel-lopes-optimizely** [comment]
@Nabil-Lahssini can you take a look now?

**Comment by Nabil-Lahssini** [comment]
@daniel-lopes-optimizely , just tested it out and it seems to work fine.
Can you please explain briefly what are the advantages of using List instead of Types please? :) I will add it in the release note.
Thank you !

**Comment by daniel-lopes-optimizely** [comment]
@Nabil-Lahssini thanks!

The Looker colour collections' mechanism uses the list order to pick which colour is displayed to the Customer next, e.g. if the collection is (red, blue, yellow, green, brown) then the mechanism starts with red for one category, then blue and so on.

Sets don't respect ordering by default, so taking the previous example we might get (brown, green, blue, red, yellow) depending on the Set's hashing algorithm. So the Customer was seeing brown graphs when it should be seeing red graphs because that's what we defined for the collection; but the tf provider was creating the colour collection with the wrong order.

Let me know if you need further info.

**Comment by Nabil-Lahssini** [comment]
Thank you for your contribution. I will release a new version during the day.

**Pull request merged**
